### PR TITLE
Use svg

### PR DESCRIPTION
**Pull request by jeremypress**
Adding a useSVG flag that can force a fallback to images through a config flag. I added tests for this as well as tests for SVG support in page-test.js

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @jeremypress, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by jeremypress** [comment]
CLA Signed!

**Comment by boxcla** [comment]
Verified that @jeremypress has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by lakenen** [comment]
Looks good to me! :+1:

**Pull request merged**
